version: '3'

services:
  frontend:
    build: ./frontend
    expose:
      - 3000
    # volumes:
    #   - ./frontend:/app

  backend:
    build: ./backend
    expose:
      - 1337
    depends_on: 
      - redis
    # volumes:
    #   - ./backend:/app

  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    depends_on: 
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
